### ISSUE TITLE
ASSOC_EXPIRE

### ISSUE THREAD

**Issue by victorclaessen** [martinius96/ESP32-Eduroam#5]
```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
Connecting to: 
eduroam
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 2 - STA_START
..[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:353] _eventCallback(): Reason: 4 - ASSOC_EXPIRE
.................
```

Is there anything I can try to get rid of the ASSOC_EXPIRE error?

**Comment by martinius96** [comment]
Hi, are you sure, you have enough WiFi signal?
It looks like your ESP disconnected due of poor WiFi signal (like AP is not available for ESP). 

It is common "issue", i see no problem there like during authentication or so on.

**Comment by victorclaessen** [comment]
I was standing in the hallway 1m below the access point, so I don't think it will get much better :-).

**Comment by martinius96** [comment]
Hmm.. I havent run any example of that my repo for more than year... 
It looks like problem is during or after autentication, when AP is going to set you IP via DHCP...
Which example have you used?
I was still using in setup program like that:
`
int counter = 0;
WiFi.disconnect(true);  //disconnect form wifi to set new wifi connection
WiFi.mode(WIFI_STA); //init wifi mode
 esp_wifi_sta_wpa2_ent_set_identity((uint8_t *)EAP_ANONYMOUS_IDENTITY, strlen(EAP_ANONYMOUS_IDENTITY)); 
 esp_wifi_sta_wpa2_ent_set_username((uint8_t *)EAP_IDENTITY, strlen(EAP_IDENTITY));
 esp_wifi_sta_wpa2_ent_set_password((uint8_t *)EAP_PASSWORD, strlen(EAP_PASSWORD));
 esp_wpa2_config_t config = WPA2_CONFIG_INIT_DEFAULT(); //set config settings to default
 esp_wifi_sta_wpa2_ent_enable(&config); //set config settings to enable function
 WiFi.begin(ssid);
while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    counter++;
    if (counter >= 60) { //after 30 seconds timeout - reset board
      ESP.restart();
    }
  }
`

**Comment by victorclaessen** [comment]
I tried both scripts of the Hasselt_university_fix. I am not at Hasselt university, however.

Perhaps I can try to see what happens if I take an incorrect username/password combination. If something different happens then indeed it could be after authentication.

`<frustration>`I'm sorry if I'm bothering you with this. After so many years with ESP8266/ESP32 I still cannot get this to work at eduroam sites. At home I have used WPA2 enterprise successfully before. What is it about eduroam and ESP that's so difficult?`</frustration>`

**Comment by martinius96** [comment]
eduroam network (under WPA/WPA2 Enterprise) is working a bit different like standard WiFi network (under WPA/WPA2-PSK). **RADIUS server that is in eduroam network will NOT inform you about bad identity or password**. It is communicating only with AP / switch, where you are connected. If authentication is good, AP will set you IP address. If not, it will ask again for identity and password, there isn't method like on standard WiFi under PSK, when AP tells you: bad password. It is not there.... It is working like that in general.

At some eduroam networks was problem and users were unable to connect to them, but we havent find issue what was problem.. **We thinked it was because of some internal configuration of RADIUS server** or something like that. 

Also one user have made Issue there, with concept of another format for identity and it was working for him. Have you tried this method? https://github.com/martinius96/ESP32-eduroam/issues/4

**Comment by victorclaessen** [comment]
At home, with control over the radius server (+access to log files), I managed to connect ESP8266 and ESP32 to WPA2 Enterprise before. At the university I have no control over RADIUS, nor can I see the logfiles.

I have also tried the uni\\user way :-S. (Both with and without escaping the backslash.)

**Comment by martinius96** [comment]
Try to ask at support of eduroam network at your university and give them MAC address of your ESP32.
They will be able to look at log and hope they will find out where is problem.
It should be because of internal configuration of radius server and they will be able to give you exception for instance to get it working :-)

**Comment by victorclaessen** [comment]
That was a good suggestion. They found in the RADIUS logs `Login incorrect (eap_peap: TLS Alert read:fatal:bad certificate)`.
So I guess that ESP32 doesn't accept the certificate that the RADIUS server presents to build a TLS tunnel for sending the PEAP credentials.

So I looked up the probable CA certificate of their RADIUS server, and added
```
const char* ca_pem = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIG5TCCBM2gAwIBAgIRANpDvROb0li7TdYcrMTz2+AwDQYJKoZIhvcNAQEMBQAw\n" \
<snip for brevity>
"Ipwgu2L/WJclvd6g+ZA/iWkLSMcpnFb+uX6QBqvD6+RNxul1FaB5iHY=\n" \
"-----END CERTIFICATE-----\n";

  if( esp_wifi_sta_wpa2_ent_set_ca_cert((uint8_t *)ca_pem, strlen(ca_pem)) ){
        Serial.println("Failed to set WPA2 CA Certificate");
        return;
    }
```
And then I got this output:
```
I (2519) wpa: WPA2 ENTERPRISE VERSION: [v2.0] enable
[D][WifiClientSecureEnterprise.ino:138] setup(): WIFI BEGIN
[D][WifiClientSecureEnterprise.ino:140] setup(): LOOP
I (2663) wifi: n:1 0, o:1 0, ap:255 255, sta:1 0, prof:1
.I (3396) wifi: state: init -> auth (b0)
I (3399) wifi: state: auth -> assoc (0)
I (3402) wifi: state: assoc -> run (10)
I (3403) wpa: wpa2_task prio:2, stack:6656

E (3415) wpa: Method private structure allocated failure

....I (5085) wpa: >>>>>wpa2 FAILED
```
So at least it seems that something changed, because the state went to 'run'. The weird thing is that this transition to run seems to happen once, but on subsequent boots it doesn't reach run, but rather reverts from assoc to init. If I erase_flash and reflash the firmware, then I reach one time the run state. Doesn't make sense to me.

I haven't received the new log files from the RADIUS server, but I'm hoping to find more clues there.

Once you start googling these things you really go down a rabbit hole of people not getting it to work. 

Anyway, now there is this error **Method private structure allocated failure**, which I managed to track to this place https://lang-ship.com/reference/ESP-IDF/4.0/esp__wpa2_8c_source.html (which probably doesn't have the same version of the esp_wpa2.c that is used in Arduino, but ok). At least now we know where this error comes from. Not really sure why it happens.

Someone commented here https://gist.github.com/me-no-dev/2d2b51b17226f5e9c5a4d9a78bdc0720#gistcomment-2624602 that it might be a string length issue. So I tried `esp_wifi_sta_wpa2_ent_set_ca_cert((uint8_t *)ca_pem, strlen(ca_pem)+1)` but that didn't seem to make a difference.

Stuck again.

**Comment by Strooom** [comment]
Hi Victor, we are trying to get the ESP32 to connect to eduroam at Fablab Kortrijk - Howest.
For the time being we have no succes. So I'd like to ask you : are certificates required to get the Wifi connected ? If so, where do we ask for them ?
Finally I see that by just adding #include "esp_wpa2.h", our memory footprint increases to 700K. We are worried that we will not have enough memory left over for the actual application.. What is your experience here?
Any further info we can share or work together to get this working ?
kind regards.

**Comment by Strooom** [comment]
Hey martinius96,  I see that University of Antwerpen UA has got this working. Are you able to share a contact person from the UA. We are in located in Antwerpen as well and would like to contact them to get this working... 
Thanks.

**Comment by victorclaessen** [comment]
I did not have any luck. My understanding is that, for PEAP, the ESP only needs to accept the certificate of the RADIUS server to allow a TLS tunnel to be created for sending the credentials. According to our RADIUS logs, my ESP does not accept any certificate.

I am not very optimistic about getting this to work. I've been trying to for years. Sometimes I find a new github repository and I get my hopes up (briefly).

**Comment by Strooom** [comment]
Thanks Victor,
we are going to put some effort in it as WPA2-Enterprise is available in most universities (eduroam) but I have also the feeling we are stretching the ESP32 beyond it's comfort zone..

**Comment by martinius96** [comment]
Something new guys?
Have you fixed it by some way?

**Comment by victorclaessen** [comment]
I have given up and am now trying to get my University to broadcast another WPA2-PSK network on the eduroam-APs. (So far, this has been equally [un]successful.)

**Comment by cbourcier3** [comment]
Hi ! 
I've seen your issue about the connection to eduroam.
In the University of Tours (France) they've recently updated the Wi-Fi network, and it now needs longer certificate (with 4096 bits RSA key) and i've tried for weeks to connect my WiPy 3.0 to the network without success. I've seen last week that the WiPy 3.0 (ESP32 based microcontroller working with micropython OS) can't connect to this wifi because he can only use certificate with 2048 or less RSA key. May this be the problem for you too ? Does your certificate has a length superior than 2048 bits ? 
I don't know if this problem is on ESP32 in general or in ESP32 with micropython SDK or only on WiPy microcontroller. 
(the source of this is on : [https://development.pycom.io/firmwareapi/pycom/network/wlan/](https://development.pycom.io/firmwareapi/pycom/network/wlan/) 
> "The ESP32 only handles certificates with pkcs8 format (but not the “Traditional SSLeay RSAPrivateKey” format). The private key should be RSA coded with 2048 bits at maximum."

If it's usually work on ESP32 i will think about using it for my project.
Thanks for the answer
