### ISSUE TITLE
Compilation error: 'WPA2_AUTH_PEAP' was not declared in this scope

### ISSUE THREAD

**Issue by paluigi** [martinius96/ESP32-Eduroam#9]
Hello,
if I try to compile and upload the new script for Arduino core 2.0.3 I get the following error:
Compilation error: 'WPA2_AUTH_PEAP' was not declared in this scope

I also get a confilct for WiFI libraries:

```
Multiple libraries were found for "WiFi.h"
  Used: /home/luigi/.arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/WiFi
  Not used: /home/luigi/Arduino/libraries/WiFiEspAT
exit status 1

Compilation error: 'WPA2_AUTH_PEAP' was not declared in this scope
```

Any hint why I get this? Should I use some different version of the WiFi library?

**Comment by martinius96** [comment]
Hi, I am not sure if it is using 2.0.3 Core WiFi.h file, because as you can see in that output, there is .../esp32/1.0.6/libraries/WiFi that means core 1.0.6. Maybe it is some problem like it updated only some libraries to 2.0.3 core. Maybe try to uninstall whole Arduino Core for ESP32 and install it again. In 2.0.3 Arduino Core compilation for me was working correctly.

Also are you using correct .json file for Arduino Core?
There are 2 json files, one is for beta versions and similar... And other is for releases.

That WPA2_AUTH_PEAP is defined in WiFiSTA.h, that is included by WiFi.h I think.
Here u can also see if you have WiFi.begin function that is awaiting that WPA method.
![definition of WPA2_AUTH_PEAP](https://i.imgur.com/MxoVo2O.png)

**Comment by paluigi** [comment]
OK, I had the wrong link for the ESP32 board in Arduino, I replaced the link with `https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json` , updated the core, and now compilation works fine! Thanks!

**Comment by martinius96** [comment]
Thanks a lot. After you try connection example, please let me know if it is working.
From time I uploaded example there, nobody informed me if it is working...
That example have Root CA or Intermediate CA for Technical university in Košice (Slovakia). 

So maybe you need other certificate of CA that issued certificate for your RADIUS server in your organization. For eduroam network you should have some... Info page of computers department where you can find certificate. You need to add it in source code in .pem format.

I am no more student and I don't have access to eduroam network, so I can't test it...

**Comment by paluigi** [comment]
I confirm the script works in my university (University of Tuscia, Italy). I am using the option without certificate. Need to test long term stability of the connection, as the ESP32 should be embedded in a smart vending machine for distributing masks to students....I will update you over time!

**Comment by martinius96** [comment]
Thanks a lot for confirmation. That's good :-)
But I am not sure if without certificate it will work on any eduroam university network.
After some updates of RADIUS servers (FreeRADIUS app on Debian servers or which it runs), they started to require certificates for more secure connection. Otherwise connection wasn't successful. For that old example for Arduino Core 1.0.X from 2019 year stopped working.

**Comment by martinius96** [comment]
I have meantime received confirmation from germany university user. Connection was working without certificate. With certificate he wasn't successful. And also he provided me important information. **There is option in configuration of RADIUS servers to exception for old and special devices.** That will enable connections without certificate. It will just verify identity and password. So this option is "luck" in your case if you were able to connect to eduroam without certificate.
